DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
CREATE TABLE IF NOT EXISTS `KEGG_COMPOUND`(
   `molecular_formula` VARCHAR(40) NOT NULL,
   `dbe` FLOAT(4) NOT NULL,
   `formula_weight` FLOAT(20) NOT NULL,
   `id` VARCHAR(20) NOT NULL,
   `description` VARCHAR(1000) NOT NULL,
   PRIMARY KEY ( `id` )
);